### ISSUE TITLE
Sync from Smart Debit not pulling mandates older than 3 months

### ISSUE THREAD

**Issue by rajeshrhino** [mattwire/org.civicrm.smartdebit#11]
@mattwire Sync from Smart Debit scheduled job is not pulling mandates/payments for SD mandates older than 3 months. 

We can see that the local cache is used when the scheduled job is executed, but this will not include any mandates older than 3 months (Eg: member paying yearly, but the mandates is not sync'd in CiviCRM)

This issue is only when running the sync via scheduled job, but works fine if we do a manual sync.

Any specific reason for having the -3 months collection report age?

**Comment by mattwire** [comment]
@rajeshrhino Which version are you testing with please?  I made a few changes in 1.17 around the caching/sync process but there may still be bugs.  I've also added a setting to change the 3 month period (the old extension was only 1 month) - it's only there because I don't know what the performance/storage impact could be of storing much larger periods - for example, the manual sync with a fixed date would take much longer if it had to download a year.  But that might be ok!

**Comment by mattwire** [comment]
@rajeshrhino The next release will default to "-1 year" as that does make sense for anyone using annual direct debits (The original veda extension used "-1 month" by the way).

**Comment by rajeshrhino** [comment]
@mattwire Yes this is fixes in latest release and is working as expected.
