### ISSUE TITLE
Issues on using Contribution 'repeattransaction' API

### ISSUE THREAD

**Issue by rajeshrhino** [mattwire/org.civicrm.smartdebit#16]
https://github.com/mattwire/org.civicrm.smartdebit/blob/53f69a10cf2c93edcf9dcbf5c1faa3d0955bdc92/CRM/Smartdebit/Sync.php#L482

There are some issues in using Contribution 'repeattransaction' API
1. Updates membership start date as well, which is not desired by many organizations.
2. Sends a contribution receipt to donor/member, not desired by some organizations, as they send DD letter before the collection

Membership start date change is the main issue here. Any of the organizations you work with has raised this?

We have made some changes to update the membership end date via API (where applicable). We just want to get some feedback/comments from you, before we commit the changes.

**Comment by mattwire** [comment]
> Updates membership start date as well, which is not desired by many organizations.

But that's standard CiviCRM behaviour... we have the "Member Since" date which won't change but the start/end dates will update each time the membership is renewed.  If there was a desire to do something different I think you would need to look at doing a PR against the repeattransaction API in core or writing a custom extension.

> Sends a contribution receipt to donor/member, not desired by some organizations, as they send DD letter before the collection

For the receipts you can turn this on/off by setting `$contributionparams['is_email_receipt']`.  I'm sure there's an extension that does this for you but I can't find it right now. But you just need to hook into the hook_civicrm_pre and match on the right contributions.
